/** Tailwind class strings for the PR intent card. Colours come from the design tokens in `@devdigest/ui/styles.css`. */
export const cx = {
  card: "flex h-full flex-col gap-4 rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] p-[18px]",
  header: "flex items-center gap-2",
  headerIcon: "text-[var(--text-muted)]",
  headerLabel: "text-[11px] font-bold uppercase tracking-[0.07em] text-[var(--text-muted)]",
  headerRight: "ml-auto flex items-center gap-2",
  quote: "m-0 text-[15px] italic leading-relaxed text-[var(--text-primary)]",
  hint: "m-0 -mt-2 text-xs text-[var(--warn)]",
  columns: "grid grid-cols-1 gap-4 sm:grid-cols-2",
  scopeLabel: "mb-2 flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-[0.07em]",
  scopeIn: "text-[var(--ok)]",
  scopeOut: "text-[var(--text-muted)]",
  list: "m-0 flex list-none flex-col gap-1.5 p-0 text-[13px] text-[var(--text-secondary)]",
  item: "flex gap-2",
  dash: "shrink-0 text-[var(--text-muted)]",
  divider: "border-0 border-t border-solid border-[var(--border)]",
  groupLabel: "mb-2 flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-[0.07em] text-[var(--text-muted)]",
  none: "text-[13px] italic text-[var(--text-muted)]",
  chips: "flex flex-wrap gap-2",
  chip: "inline-flex max-w-full items-center gap-1.5 rounded-md border border-[var(--border)] bg-[var(--bg-surface)] px-2 py-1 text-xs text-[var(--text-secondary)]",
  chipText: "truncate",
  conflicts: "m-0 flex flex-col gap-1 text-xs text-[var(--warn)]",
  footer: "flex flex-col gap-1.5 text-xs text-[var(--text-muted)]",
  sources: "flex flex-wrap items-center gap-x-3 gap-y-1",
  source: "inline-flex items-center gap-1 text-[var(--text-secondary)]",
  sourceRef: "mono",
  muted: "text-[var(--text-muted)]",
  stateText: "m-0 text-sm text-[var(--text-secondary)]",
  stateHint: "m-0 text-[13px] text-[var(--text-muted)]",
  skeletons: "flex flex-col gap-2",
} as const;
